# Generated by Django 4.2 on 2024-10-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.competence', verbose_name='Компетенция')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Оценка')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.grade', verbose_name='Грейд')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.position', verbose_name='Позиция')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.skill', verbose_name='Навык')),
            ],
        ),
        migrations.CreateModel(
            name='RequestTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_result', models.CharField(max_length=100, verbose_name='Желаемый результат')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(max_length=100, verbose_name='Статус запроса')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.employee', verbose_name='Сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.skill', verbose_name='Навык')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('evaluation', models.CharField(max_length=100, verbose_name='Оценка эксперта')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.employee', verbose_name='Сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.skill', verbose_name='Навык')),
            ],
        ),
    ]
