# Generated by Django 4.2 on 2024-10-11 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Domen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.competence', verbose_name='Компетенция')),
            ],
        ),
        migrations.CreateModel(
            name='PositionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Оценка')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.grade', verbose_name='Грейд')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.position', verbose_name='Позиция')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.skill', verbose_name='Грейд')),
            ],
        ),
        migrations.AddField(
            model_name='competence',
            name='domen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.domen', verbose_name='домен'),
        ),
        migrations.AddField(
            model_name='competence',
            name='type_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.typeskill', verbose_name='Компетенция'),
        ),
    ]
