# Generated by Django 4.2 on 2024-10-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0002_competence_requirementposition_skill_delete_skil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementposition',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.grade', verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='requirementposition',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.skill', verbose_name='Грейд'),
        ),
    ]
