# Generated by Django 4.2 on 2024-10-11 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=100, verbose_name='Имя')),
                ('bus_factor', models.BooleanField(verbose_name='Бас фактор')),
                ('key', models.BooleanField(verbose_name='Ключевой сотрудник')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.grade', verbose_name='Грейд')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.position', verbose_name='Позиция')),
            ],
            options={
                'default_related_name': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.employee', verbose_name='Позиция')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.grade', verbose_name='Грейд')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.position', verbose_name='Позиция')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BooleanField(verbose_name='Ключевой навык')),
                ('education_request', models.BooleanField(verbose_name='Образовательный запрос')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.employee', verbose_name='Позиция')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.skill', verbose_name='Скил')),
            ],
            options={
                'default_related_name': 'employee_skill',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.IntegerField(verbose_name='Оценка')),
                ('accordance', models.BooleanField(verbose_name='Соответствие')),
                ('education_progress', models.BooleanField(verbose_name='Обучается')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.employee', verbose_name='Позиция')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.skill', verbose_name='Скил')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда'),
        ),
    ]
