# Generated by Django 4.2 on 2024-10-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('bus_factor', models.BooleanField(verbose_name='Бас фактор')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.grade', verbose_name='Гейд')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.position', verbose_name='Позиция')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='TargetEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.employee')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.grade', verbose_name='Гейд')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.position', verbose_name='Позиция')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.employee', verbose_name='Сотрудник')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда')),
            ],
        ),
    ]
