# Generated by Django 4.2 on 2024-10-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0002_competence_requirementposition_skill_delete_skil_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_result', models.CharField(max_length=100, verbose_name='Желаемый результат')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(max_length=100, verbose_name='Статут запроса')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.employee', verbose_name='Сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.skill', verbose_name='Скилл')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('evaluation', models.CharField(max_length=100, verbose_name='Оценка эксперта')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.employee', verbose_name='Сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.skill', verbose_name='Скилл')),
            ],
        ),
    ]
