# Generated by Django 4.2 on 2024-10-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0003_alter_requirementposition_grade_and_more'),
        ('teams', '0002_requesttraining_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.grade', verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='employeeteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_team', to='teams.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='targetemployee',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.grade', verbose_name='Грейд'),
        ),
    ]
